Restauracja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Restauracja_app.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('restauracja_app/', include('Restauracja_app.urls')),
    path('accounts/', include('Accounts.urls')),
    path('Waiter/', include('Waiter.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Waiter/urls.py
from django.urls import path
from Waiter.views import Index_Waiter, Menu_View, Order_View
from Waiter.cart_waiter import add_to_cart_waiter, remove_from_cart_waiter
urlpatterns = [
    path('waiter_index/', Index_Waiter.as_view(), name='index_waiter'),
    path('waiter_menu/<slug>/', Menu_View.as_view(), name='waiter_menu'),
    path('waiter_order/<slug>/', Order_View.as_view(), name='waiter_order'),
    path('add_to_card_waiter/<pk>/', add_to_cart_waiter, name='add_to_card_waiter'),
    path('remove-from-cart/<pk>/', remove_from_cart_waiter, name='remove_from_cart_waiter'),
]

Restauracja_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=200)
    slug = models.CharField(max_length=64, unique=True)
    image = models.ImageField(blank=True, upload_to='category_images')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Kategoria"
        verbose_name_plural = 'Kategorie'

    def get_absolute_url(self):
        return reverse('update_category', args=(self.pk,))

    def get_delete_url(self):
        return reverse('delete_category', args=(self.pk,))

class Menu(models.Model):
    name = models.CharField(max_length=64)
    ingredients = models.TextField()
    description = models.TextField()
    price = models.FloatField()
    votes = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='menu_images')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Menu"
        verbose_name_plural = 'Menu'

    def get_update_menu(self):
        return reverse('update_menu', args=(self.pk,))

    def get_delete_menu(self):
        return reverse('delete_menu', args=(self.pk,))

    def get_add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={
            "pk": self.pk
        })

    def get_add_to_cart_waiter_url(self):
        return reverse("add_to_card_waiter", kwargs={
            "pk": self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("remove-from-cart", kwargs={
            "pk": self.pk
        })

    def get_remove_from_cart_waiter_url(self):
        return reverse("remove_from_cart_waiter", kwargs={
            "pk": self.pk
        })


class Comments(models.Model):
    title = models.CharField(max_length=120)
    meal = models.ForeignKey(Menu, on_delete=models.CASCADE)
    text = models.TextField()
    author = models.CharField(max_length=64)
    data_create = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Komentarz'
        verbose_name_plural = 'Komentarze'


class Table(models.Model):
    name = models.CharField(max_length=64)
    number_of_seats = models.IntegerField()
    availability = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_update_table(self):
        return reverse('update_table', args=(self.pk,))

    def get_delete_table(self):
        return reverse('delete_table', args=(self.pk,))


class Reserve(models.Model):
    date = models.DateField()
    time = models.TimeField()
    last_name = models.CharField(max_length=64)
    tables = models.ForeignKey(Table, on_delete=models.CASCADE)
    realized = models.BooleanField(default=False, help_text='Nie')

    def get_realized_reserve(self):
        return reverse('realized_reserve', args=(self.pk,))


class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    meal = models.ForeignKey(Menu, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.meal.name}"

    def get_total_item_price(self):
        return self.quantity * self.meal.price


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    meals = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField()

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for order_item in self.meals.all():
            total += order_item.get_total_item_price()
        return total

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load auth_extras %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">
    <title>Zielony zakątek</title>
    <link rel="stylesheet" href="{% static "base.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
 <header class="page-header">
        <nav class="navbar navbar-expand-lg justify-content-around">
            <a href="/" class="navbar-brand main-logo">
                Zielony <span>Zakątek</span>
            </a>
            <ul class="nav nounderline text-uppercase">
                <li class="nav-item ml-4">
                    <a class="nav-link" href="http://127.0.0.1:8000/restauracja_app/about/">O nas</a>
                </li>
                <li class="nav-item ml-4">
                    <a class="nav-link" href="http://127.0.0.1:8000/restauracja_app/table_list/">Zarezerwuj stolik</a>
                </li>
                <li class="nav-item ml-4">
                    <a class="nav-link" href="http://127.0.0.1:8000/restauracja_app/category/">Menu</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item ml-4">
                    <a class="nav-link " href="http://127.0.0.1:8000/accounts/login/">logowanie</a>
                </li>
                <li class="nav-item ml-4">
                    <a class="nav-link " href="http://127.0.0.1:8000/accounts/registration/">rejestracja</a>
                </li>
                {% else %}
                <li class="nav-item ml-4">
                    <a class="nav-link"  href="http://127.0.0.1:8000/accounts/logout/">Wyloguj</a>
                </li>
                {% endif %}
                <li class="nav-item ml-4">
                    <a class="nav-link"  href="http://127.0.0.1:8000/restauracja_app/order-details/">Koszyk</a>
                </li>
            {% if user.is_authenticated %}
                <li>
                    <p class="nav-link">Witaj: {{ user.first_name }}</p>
                </li>
            {% endif %}
            </ul>

<div class="dropdown">
{% if user.is_authenticated and request.user|has_group:"Pracownicy" %}
  <button class="dropbtn">Więcej</button>
  <div class="dropdown-content">
    {% if perms.Restauracja_app.add_category %}
        <a href="http://127.0.0.1:8000/restauracja_app/add_category/">Dodaj kategorie</a>
    {% endif %}
    {% if perms.Restauracja_app.add_menu %}
        <a href="http://127.0.0.1:8000/restauracja_app/add_menu/">Dodaj Danie</a>
    {% endif %}
  {% if perms.Restauracja_app.view_reserve %}
    <a href="http://127.0.0.1:8000/restauracja_app/reserve_list/">Rezerwacje</a>
  {% endif %}

  <a href="http://127.0.0.1:8000/Waiter/waiter_index/">Obsługa kelnerska</a>

  </div>
{% endif %}
</div>

        </nav>
    </header>
    {% block content %}
    {% endblock %}



</body>
</html>

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row row-cols-1 row-cols-md-2 g-4">
  {% for cat in category %}
    <div class="col">
        <div class="card" style="width: 40rem; margin: auto">
            {% if cat.image %}
                <img src="{{ cat.image.url }}" class="card-img-top" alt="...">
            {% endif %}
        <div class="card-body text-center">
              <h5 class="nav-link active"><a href="http://127.0.0.1:8000/restauracja_app/menu_list/{{ cat.slug }}">{{ cat.name }}</a></h5>

            <p class="card-text">{{ cat.description }}</p>
                {% if perms.Restauracja_app.change_category %}
        <a class="card-link" href="{{ cat.get_absolute_url }}">Edytuj</a>
  {% endif %}
  {% if perms.Restauracja_app.delete_category %}
        <a class="card-link" href="{{ cat.get_delete_url }}">Usuń</a>
{% endif %}
        </div>
        </div>
    </div>
{% endfor %}
    </div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block content %}
<section class="form_box">
<form method="post" class="form">
	<div style="margin:80px">
		<h1 class="form_title">Kontakt</h1>
        {% csrf_token %}
    {% for field in form %}
    {{ field.label }}<br>
    {{ field }}<br>
        {% endfor %}
            <button class="form_button" type="submit">Wyślij</button>
    </div>
</form>
</section>
{% endblock %}

templates/delete_form.html
{% extends 'base.html' %}
{% block content %}
<section class="form_box">
<form class="form" method="post">
    {% csrf_token %}
    <p class="text-form">Czy na pewno chcesz usunąć wybraną pozycję: {{ category.name }} {{ menu.name }} {{ table.name }}?</p>
    <input class="form_button" type="submit" value="Usuń">
    <a href="{{ view.get_success_url }}" class="form_button">Cancel</a>

</form>
</section>
{% endblock %}

templates/edit_form.html
{% extends 'base.html' %}
{% block content %}
<section class="form_box">
<form class="form" method="post">
{% csrf_token %}
    <h2 class="form_title">Edytuj</h2>
    {% for field in form %}
    {{ field.label }}<br>
    {{ field }}
   {% endfor %}
<input class="form_button" type="submit" value="Zapisz">
</form>
</section>
{% endblock %}

templates/form_login.html
{% extends 'base.html' %}
{% block content %}
<section class="form_box">
<form class="form" method="post">
{% csrf_token %}
    <h2 class="form_title">Logowanie</h2>
    {% for field in form %}
    {{ field.label }}<br>
    {{ field }}
   {% endfor %}
<input class="form_button" type="submit" value="Zaloguj">
<h2 class="form_button"><a href="http://127.0.0.1:8000/accounts/registration/">Rejestracja</a> </h2>
</form>
</section>
{% endblock %}

templates/menu_details.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3">
{% if menu.image %}
  <img src="{{ menu.image.url }}" class="card-img-top" style="height: 500px; width: 600px; margin: auto;" alt="...">
{% endif %}
  <div class="card-body text-center">
    <h5 class="card-title">{{ menu.name }}</h5>
    <p class="card-text">{{ menu.description }}</p>
    <p class="card-text">{{ menu.ingredients }}</p>
    <p class="card-text">{{ menu.price }} zł</p>
    <p class="card-text">Ocena: {{ menu.votes }}</p>
    <a href="{{ menu.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >Dodaj do koszyka
                <i class="fas fa-shopping-cart ml-1"></i></a>

<form action="" method="post">
        {% csrf_token %}
    <input type="hidden" name="recipe_id" value={{ recipe.id }}>
        <button type="submit" name="vote" value="1" class="btn btn-success">
             Lubię To &#128077;
        </button>
        <button type="submit" name="vote" value="-1" class="btn btn-danger thumbs up sign">
             Nie Lubię &#128078;
        </button>
</form>
  <h3 class="form_title">Dodaj komentarz</h3>
<section class="form_box">
    <form class="form" action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }}<br>
            {{ field }}
        {% endfor %}
        <input class="form_button" type="submit" name="dodaj" value="Dodaj">
    </form>
</section>
<h3 class="form_title">Komentarze</h3>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for i in comment %}
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Tytuł:<br>{{ i.title }}</h5>
        <p class="card-text">Autor:<br>{{ i.author }}</p>
        <p class="card-text">Komentarz:<br>{{ i.text }}</p>
      </div>
    </div>
  </div>
    {% endfor %}
</div>
  </div>
</div>
{% endblock %}

templates/order_card.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div class= "container">
        <div class="table-responsive text-nowrap">
    <h3>
        <strong>Twój koszyk</strong>
    </h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nazwa Posiłku</th>
            <th scope="col">Cena</th>
            <th scope="col">Ilość</th>
            <th scope="col">Cena razem</th>
        </tr>
        </thead>
        <tbody>
        {% for meal_item in order.meals.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ meal_item.meal.name }}</td>
            <td>{{ meal_item.meal.price|floatformat:2}}zł</td>
            <td>

                {{ meal_item.quantity }}
                <a href="{% url 'add-to-cart' meal_item.meal.pk %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>{{ meal_item.get_total_item_price|floatformat:2}}zł
             <a href="{% url 'remove-from-cart' meal_item.meal.pk %}">
                <i class="fas fa-trash float-right text-danger"></i>
             </a>
            </td>
        </tr>

        {% empty %}
        <tr>
            <td colspan="5">Twój koszyk jest pusty</td>
        </tr>

         <tr>
            <td colspan="5">
                <a href="http://127.0.0.1:8000/restauracja_app/category/" class="btn btn-primary float-right">Kontynuuj Zapupy</a>
            </td>
        </tr>
        {% endfor %}

        {% if order.get_total_price %}
        <tr>
            <td colspan="4"><b>Razem do zapłaty</b></td>
            <td>{{ order.get_total_price|floatformat:2 }}zł</td>
        </tr>
         <tr>
            <td colspan="5">
                <a href="http://127.0.0.1:8000/restauracja_app/category/" class="btn btn-primary float-right">Kontynuuj Zapupy </a>
            </td>
         </tr>
         <tr>
         <td colspan="5">
                <a href="" class="btn btn-primary float-right">Przejdz do kasy </a>
            </td>
        </tr>

        {% endif %}

        </tbody>
    </table>

        </div>
    </div>
</main>

{% endblock content %}

templates/reserve.html
{% extends 'base.html' %}
{% block content %}
<section class="form_box">
    <form class="form" action="" method="POST">
        {% csrf_token %}
        <h2 class="form_title">Rezerwujesz stolik:<br>{{ table.name }}</h2>
        <div class="first_form">
            <label class="name_label" id="lat_name">Nazwisko:</label>
            <input class="name_input" type="text" name="last_name" placeholder="Nazwisko" >
            <label class="name_label" id="date">Data:</label>
            <input class="name_input" type="date" name="date" placeholder="Data" >
            <label class="name_label" id="date">Czas:</label>
            <input class="name_input" type="time" name="time" placeholder="Czas" >
        </div>
        <input class ="form_button" type="submit" value="Rezerwuj">
        <div>
        <h2>Rezeracje:</h2>
            <ul>
            {% for tab in reservations %}
            <p>Data rezeracji: <b>{{ tab.date }} {{ tab.time }}</b></p>
            {% endfor %}
            </ul>
        </div>
    </form>
</section>
{% if error %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{error}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
{% endblock %}

templates/reserve_list.html
{% extends 'base.html' %}
{% block content %}
<header>
    <h2>Lista rezerwacji </h2>
<table class="table">
    <thead class="table">
      <tr>
         <th>ID</th> <th>Nazwa Stolika</th> <th>Ilośc miejsc</th><th>Data</th><th>Czas</th><th>Nazwisko</th><th>Zrealizowana</th>

      </tr>
   </thead>
   <tbody>
    {% for i in reserve %}
        <td>{{ i.id }}</td>
        <td>{{ i.tables.name }}</td>
        <td>{{ i.tables.number_of_seats }}</td>
        <td>{{ i.date }}</td>
        <td>{{ i.time }}</td>
        <td>{{ i.last_name }}</td>
        <td>{{ i.realized|yesno }}
        </td>
        <td><a href="{{ i.get_realized_reserve }}">Zrealizowana</a> </td>

    </tbody>

    {% endfor %}
</table>
</header>
{% endblock %}

templates/table_list.html
{% extends 'base.html' %}
{% block content %}
<header>
    <h2>Lista Stolików </h2>
<table class="table">
    <thead class="table">
      <tr>
         <th>ID</th> <th>Nazwa Stolika</th> <th>Ilośc miejsc</th><th>Dostępność stolika na dzień {{ date }}</th>

      </tr>
   </thead>
   <tbody>
    {% for i in table %}
        <td>{{ i.id }}</td>
        <td>{{ i.name }}</td>
        <td>{{ i.number_of_seats }}</td>
        {% if i.reserved %}
            <td>Zarezerowoany</td>
        {% else %}
            <td>Dostępny</td>
        {% endif %}
        {% if perms.Restauracja_app.change_table %}
        <td><a href="{{ i.get_update_table }}">Edutyj</a> </td>
        {% endif %}
        {% if perms.Restauracja_app.delete_table %}
        <td><a href="{{ i.get_delete_table }}">Usuń</a> </td>
        {% endif %}
        <td><a href="http://127.0.0.1:8000/restauracja_app/reserve/{{ i.id }}/">Rezerwuj</a></td>
        </tbody>
    {% endfor %}
</table>
<h3 style="text-align: center">LUB</h3>
<h2 style="text-align: center"><a href="http://127.0.0.1:8000/restauracja_app/contact">Skontaktuj się z nami</a> </h2>
</header>
{% endblock %}

templates/waiter_card.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<h4>Wybierz kategorie w której znajduje się danie wybrane przez klienta lub polec sam wybraną przez siebie kategorie:</h4>
<div class="btn-group">
    {% for i in category %}
  <a href="http://127.0.0.1:8000/Waiter/waiter_menu/{{ i.slug }}/" class="btn btn-primary">{{ i.name }}</a>
    {% endfor %}
</div><br><br>
<h4>Wybierz danie wybrane przez klienta a doda się do zamówienia</h4><br>
<div class="btn-group">
    {% for i in menu %}
  <a href="{{ i.get_add_to_cart_waiter_url }}" class="btn btn-primary">{{ i.name }}</a>
    {% endfor %}
</div>
<main>
    <div class= "container">
        <div class="table-responsive text-nowrap">
    <h3>
        <strong>Twój koszyk</strong>
    </h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nazwa Posiłku</th>
            <th scope="col">Cena</th>
            <th scope="col">Ilość</th>
            <th scope="col">Cena razem</th>
        </tr>
        </thead>
        <tbody>
        {% for meal_item in order.meals.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ meal_item.meal.name }}</td>
            <td>${{ meal_item.meal.price|floatformat:2}}</td>
            <td>
{#                <a href="{% url 'core:reduce-quantity-item' meal_item.item.pk %}"><i class="fas fa-minus mr-2"></i></a>#}
                {{ meal_item.quantity }}
                <a href="{% url 'add-to-cart' meal_item.meal.pk %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>${{ meal_item.get_total_item_price|floatformat:2}}
             <a href="{% url 'remove-from-cart' meal_item.meal.pk %}">
                <i class="fas fa-trash float-right text-danger"></i>
             </a>
            </td>
        </tr>

        {% empty %}
        <tr>
            <td colspan="5">Twój koszyk jest pusty</td>
        </tr>

         <tr>
            <td colspan="5">
                <a href="http://127.0.0.1:8000/restauracja_app/category/" class="btn btn-primary float-right">Kontynuuj Zapupy</a>
            </td>
        </tr>
        {% endfor %}

        {% if order.get_total_price %}
        <tr>
            <td colspan="4"><b>Razem do zapłaty</b></td>
            <td>${{ order.get_total_price|floatformat:2 }}</td>
        </tr>
         <tr>
            <td colspan="5">
{#                <a href="{% url 'checkout' %}" class="btn btn-warning float-right ml-2">Checkout</a>#}
                <a href="http://127.0.0.1:8000/restauracja_app/category/" class="btn btn-primary float-right">Kontynuuj Zapupy </a>
            </td>
        </tr>

        {% endif %}

        </tbody>
    </table>

        </div>
    </div>
</main>

templates/waiter_menu.html
{% extends 'base.html' %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<div class="btn-group">
    <a href="http://127.0.0.1:8000/restauracja_app/reserve_list/" class="btn btn-primary">Rezerwacje</a>
</div><br>
<h4>Wybierz kategorie w której znajduje się danie wybrane przez klienta lub polec sam wybraną przez siebie kategorie:</h4>
<div class="btn-group">
    {% for i in category %}
  <a href="http://127.0.0.1:8000/Waiter/waiter_menu/{{ i.slug }}/" class="btn btn-primary">{{ i.name }}</a>
    {% endfor %}

</div><br><br>
<h4>Wybierz danie wybrane przez klienta a doda się do zamówienia</h4><br>
<div class="btn-group">
    {% for i in menu %}
  <a href="{{ i.get_add_to_cart_waiter_url }}" class="btn btn-primary">{{ i.name }}</a>
    {% endfor %}
</div>

{% endblock %}

templates/waiter_order.html
{% extends 'base.html' %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<div class="btn-group">
    <a href="http://127.0.0.1:8000/restauracja_app/reserve_list/" class="btn btn-primary">Rezerwacje</a>
</div><br>
<h4>Wybierz kategorie w której znajduje się danie wybrane przez klienta lub polec sam wybraną przez siebie kategorie:</h4>
<div class="btn-group">
    {% for i in category %}
  <a href="http://127.0.0.1:8000/Waiter/waiter_menu/{{ i.slug }}/" class="btn btn-primary">{{ i.name }}</a>
    {% endfor %}

</div><br><br>
<h4>Wybierz danie wybrane przez klienta a doda się do zamówienia</h4><br>
<div class="btn-group">
    {% for i in menu %}
  <a href="{{ i.get_add_to_cart_waiter_url }}" class="btn btn-primary">{{ i.name }}</a>
    {% endfor %}
</div>
<main>
    <div class= "container">
        <div class="table-responsive text-nowrap">
    <h3>
        <strong>Twój koszyk</strong>
    </h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nazwa Posiłku</th>
            <th scope="col">Cena</th>
            <th scope="col">Ilość</th>
            <th scope="col">Cena razem</th>
        </tr>
        </thead>
        <tbody>
        {% for meal_item in order.meals.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ meal_item.meal.name }}</td>
            <td>{{ meal_item.meal.price|floatformat:2}}zł</td>
            <td>
{#                <a href="{% url 'core:reduce-quantity-item' meal_item.item.pk %}"><i class="fas fa-minus mr-2"></i></a>#}
                {{ meal_item.quantity }}
                <a href="{% url 'add_to_card_waiter' meal_item.meal.pk %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>{{ meal_item.get_total_item_price|floatformat:2}}zł
             <a href="{% url 'remove_from_cart_waiter' meal_item.meal.pk %}">
                <i class="fas fa-trash float-right text-danger"></i>
             </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">Twój koszyk jest pusty</td>
        </tr>
        {% endfor %}
        {% if order.get_total_price %}
        <tr>
            <td colspan="4"><b>Razem do zapłaty</b></td>
            <td>{{ order.get_total_price|floatformat:2 }}zł</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
        </div>
    </div>
</main>

{% endblock %}